//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.23 at 04:35:56 PM IST 
//


package in.wynk.sms.lobby;

/**
 * <p>Java class for form complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="form"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="da" type="{https://medium.com/article}contact"/&gt;
 *         &lt;element name="oa" type="{https://medium.com/article}sender"/&gt;
 *         &lt;element name="ud" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dcs" type="{https://medium.com/article}communication"/&gt;
 *         &lt;element name="statusrequest" type="{https://medium.com/article}blank"/&gt;
 *         &lt;element name="from" type="{https://medium.com/article}client"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
public class Form {


    protected Contact da;
    protected Sender oa;
    protected String ud;
    protected Communication dcs;
    protected Blank statusrequest;
    protected Wrapper from;
    protected String to;

    /**
     * Gets the value of the from property.
     *
     * @return
     *     possible object is
     *     {@link Wrapper }
     *
     */
    public Wrapper getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     *
     * @param value
     *     allowed object is
     *     {@link Wrapper }
     *
     */
    public void setFrom(Wrapper value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTo(String value) {
        this.to = value;
    }

    /**
     * Gets the value of the da property.
     * 
     * @return
     *     possible object is
     *     {@link Contact }
     *     
     */
    public Contact getDa() {
        return da;
    }

    /**
     * Sets the value of the da property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contact }
     *     
     */
    public void setDa(Contact value) {
        this.da = value;
    }

    /**
     * Gets the value of the oa property.
     * 
     * @return
     *     possible object is
     *     {@link Sender }
     *     
     */
    public Sender getOa() {
        return oa;
    }

    /**
     * Sets the value of the oa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sender }
     *     
     */
    public void setOa(Sender value) {
        this.oa = value;
    }

    /**
     * Gets the value of the ud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUd() {
        return ud;
    }

    /**
     * Sets the value of the ud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUd(String value) {
        this.ud = value;
    }

    /**
     * Gets the value of the dcs property.
     * 
     * @return
     *     possible object is
     *     {@link Communication }
     *     
     */
    public Communication getDcs() {
        return dcs;
    }

    /**
     * Sets the value of the dcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Communication }
     *     
     */
    public void setDcs(Communication value) {
        this.dcs = value;
    }

    /**
     * Gets the value of the statusrequest property.
     * 
     * @return
     *     possible object is
     *     {@link Blank }
     *     
     */
    public Blank getStatusrequest() {
        return statusrequest;
    }

    /**
     * Sets the value of the statusrequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Blank }
     *     
     */
    public void setStatusrequest(Blank value) {
        this.statusrequest = value;
    }

}
