//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.23 at 04:35:56 PM IST 
//


package in.wynk.sms.lobby;

/**
 * <p>Java class for communication complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="communication"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mclass" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="coding" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
public class Communication {

    protected int mclass;
    protected int coding;

    /**
     * Gets the value of the mclass property.
     * 
     */
    public int getMclass() {
        return mclass;
    }

    /**
     * Sets the value of the mclass property.
     * 
     */
    public void setMclass(int value) {
        this.mclass = value;
    }

    /**
     * Gets the value of the coding property.
     * 
     */
    public int getCoding() {
        return coding;
    }

    /**
     * Sets the value of the coding property.
     * 
     */
    public void setCoding(int value) {
        this.coding = value;
    }

}
